"""Reference seed data for a fresh KonzertKatalog database.

Contains the 30 most-performed classical composers with their major works
and ~60 well-known concert artists (conductors and soloists).

Seeding runs automatically the first time the application starts with an
empty database.  To re-seed: delete the database file — it will be
recreated with fresh reference data on next launch.

To modify: edit COMPOSERS or ARTISTS below.  Each composer entry accepts:
  first_name, last_name, birth_year, death_year, catalogue (prefix string),
  pieces: list of (title, key, catalogue_number)

Leave catalogue_number="" for works without a reliable number.
"""

from loguru import logger
from sqlalchemy.orm import Session

from app.models import Artist, Composer, Piece

# ---------------------------------------------------------------------------
# Composers & pieces
# Pieces: (title, key, catalogue_number)  — key and catalogue_number may be ""
# ---------------------------------------------------------------------------
COMPOSERS: list[dict] = [
    {
        "first_name": "Ludwig van",
        "last_name": "Beethoven",
        "birth_year": 1770,
        "death_year": 1827,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 3 «Eroica»", "Es-Dur", "55"),
            ("Sinfonie Nr. 5", "c-Moll", "67"),
            ("Sinfonie Nr. 6 «Pastorale»", "F-Dur", "68"),
            ("Sinfonie Nr. 7", "A-Dur", "92"),
            ("Sinfonie Nr. 9", "d-Moll", "125"),
            ("Klavierkonzert Nr. 3", "c-Moll", "37"),
            ("Klavierkonzert Nr. 4", "G-Dur", "58"),
            ("Klavierkonzert Nr. 5 «Emperor»", "Es-Dur", "73"),
            ("Violinkonzert", "D-Dur", "61"),
            ("Tripelkonzert", "C-Dur", "56"),
            ("Ouvertüre «Egmont»", "f-Moll", "84"),
            ("Missa solemnis", "D-Dur", "123"),
        ],
    },
    {
        "first_name": "Wolfgang Amadeus",
        "last_name": "Mozart",
        "birth_year": 1756,
        "death_year": 1791,
        "catalogue": "KV",
        "pieces": [
            ("Eine kleine Nachtmusik", "G-Dur", "525"),
            ("Sinfonie Nr. 39", "Es-Dur", "543"),
            ("Sinfonie Nr. 40", "g-Moll", "550"),
            ("Sinfonie Nr. 41 «Jupiter»", "C-Dur", "551"),
            ("Sinfonie Nr. 38 «Prager»", "D-Dur", "504"),
            ("Sinfonie Nr. 35 «Haffner»", "D-Dur", "385"),
            ("Sinfonie Nr. 36 «Linzer»", "C-Dur", "425"),
            ("Klavierkonzert Nr. 20", "d-Moll", "466"),
            ("Klavierkonzert Nr. 21", "C-Dur", "467"),
            ("Klavierkonzert Nr. 23", "A-Dur", "488"),
            ("Klavierkonzert Nr. 24", "c-Moll", "491"),
            ("Klarinettenkonzert", "A-Dur", "622"),
            ("Violinkonzert Nr. 3", "G-Dur", "216"),
            ("Violinkonzert Nr. 5 «Türkisches»", "A-Dur", "219"),
            ("Sinfonia concertante", "Es-Dur", "364"),
            ("Klarinettenquintett", "A-Dur", "581"),
            ("Requiem", "d-Moll", "626"),
            ("Die Zauberflöte", "", "620"),
            ("Le nozze di Figaro", "", "492"),
            ("Don Giovanni", "", "527"),
        ],
    },
    {
        "first_name": "Johann Sebastian",
        "last_name": "Bach",
        "birth_year": 1685,
        "death_year": 1750,
        "catalogue": "BWV",
        "pieces": [
            ("Matthäus-Passion", "", "244"),
            ("Johannes-Passion", "", "245"),
            ("Messe", "h-Moll", "232"),
            ("Weihnachtsoratorium", "", "248"),
            ("Brandenburgisches Konzert Nr. 1", "F-Dur", "1046"),
            ("Brandenburgisches Konzert Nr. 2", "F-Dur", "1047"),
            ("Brandenburgisches Konzert Nr. 3", "G-Dur", "1048"),
            ("Brandenburgisches Konzert Nr. 4", "G-Dur", "1049"),
            ("Brandenburgisches Konzert Nr. 5", "D-Dur", "1050"),
            ("Brandenburgisches Konzert Nr. 6", "B-Dur", "1051"),
            ("Orchestersuite Nr. 2", "h-Moll", "1067"),
            ("Orchestersuite Nr. 3", "D-Dur", "1068"),
            ("Violinkonzert Nr. 1", "a-Moll", "1041"),
            ("Violinkonzert Nr. 2", "E-Dur", "1042"),
            ("Doppelviolinkonzert", "d-Moll", "1043"),
            ("Cembalokonzert Nr. 1", "d-Moll", "1052"),
            ("Toccata und Fuge", "d-Moll", "565"),
            ("Goldberg-Variationen", "", "988"),
        ],
    },
    {
        "first_name": "Johannes",
        "last_name": "Brahms",
        "birth_year": 1833,
        "death_year": 1897,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 1", "c-Moll", "68"),
            ("Sinfonie Nr. 2", "D-Dur", "73"),
            ("Sinfonie Nr. 3", "F-Dur", "90"),
            ("Sinfonie Nr. 4", "e-Moll", "98"),
            ("Klavierkonzert Nr. 1", "d-Moll", "15"),
            ("Klavierkonzert Nr. 2", "B-Dur", "83"),
            ("Violinkonzert", "D-Dur", "77"),
            ("Doppelkonzert", "a-Moll", "102"),
            ("Ein deutsches Requiem", "", "45"),
            ("Akademische Festouvertüre", "", "80"),
            ("Tragische Ouvertüre", "", "81"),
            ("Variationen über ein Thema von Haydn", "", "56a"),
        ],
    },
    {
        "first_name": "Pjotr Iljitsch",
        "last_name": "Tschaikowski",
        "birth_year": 1840,
        "death_year": 1893,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 4", "f-Moll", "36"),
            ("Sinfonie Nr. 5", "e-Moll", "64"),
            ("Sinfonie Nr. 6 «Pathétique»", "h-Moll", "74"),
            ("Klavierkonzert Nr. 1", "b-Moll", "23"),
            ("Violinkonzert", "D-Dur", "35"),
            ("Ouvertüre «1812»", "Es-Dur", "49"),
            ("Romeo und Julia (Fantasie-Ouvertüre)", "", ""),
            ("Schwanensee", "", "20"),
            ("Nussknacker-Suite", "", "71a"),
            ("Dornröschen", "", "66"),
            ("Serenade für Streicher", "C-Dur", "48"),
            ("Rokoko-Variationen", "", "33"),
        ],
    },
    {
        "first_name": "Gustav",
        "last_name": "Mahler",
        "birth_year": 1860,
        "death_year": 1911,
        "catalogue": "",
        "pieces": [
            ("Sinfonie Nr. 1 «Titan»", "D-Dur", ""),
            ("Sinfonie Nr. 2 «Auferstehung»", "c-Moll", ""),
            ("Sinfonie Nr. 3", "d-Moll", ""),
            ("Sinfonie Nr. 4", "G-Dur", ""),
            ("Sinfonie Nr. 5", "cis-Moll", ""),
            ("Sinfonie Nr. 6", "a-Moll", ""),
            ("Sinfonie Nr. 7", "e-Moll", ""),
            ("Sinfonie Nr. 8 «Sinfonie der Tausend»", "Es-Dur", ""),
            ("Sinfonie Nr. 9", "D-Dur", ""),
            ("Das Lied von der Erde", "", ""),
            ("Kindertotenlieder", "", ""),
        ],
    },
    {
        "first_name": "Anton",
        "last_name": "Bruckner",
        "birth_year": 1824,
        "death_year": 1896,
        "catalogue": "",
        "pieces": [
            ("Sinfonie Nr. 3", "d-Moll", ""),
            ("Sinfonie Nr. 4 «Romantische»", "Es-Dur", ""),
            ("Sinfonie Nr. 5", "B-Dur", ""),
            ("Sinfonie Nr. 6", "A-Dur", ""),
            ("Sinfonie Nr. 7", "E-Dur", ""),
            ("Sinfonie Nr. 8", "c-Moll", ""),
            ("Sinfonie Nr. 9", "d-Moll", ""),
            ("Te Deum", "C-Dur", ""),
        ],
    },
    {
        "first_name": "Franz",
        "last_name": "Schubert",
        "birth_year": 1797,
        "death_year": 1828,
        "catalogue": "D.",
        "pieces": [
            ("Sinfonie Nr. 8 «Unvollendete»", "h-Moll", "759"),
            ("Sinfonie Nr. 9 «Große»", "C-Dur", "944"),
            ("Klavierquintett «Forellenquintett»", "A-Dur", "667"),
            ("Streichquintett", "C-Dur", "956"),
            ("Messe Nr. 6", "Es-Dur", "950"),
            ("Rosamunde (Schauspielmusik)", "", "797"),
            ("Winterreise", "", "911"),
        ],
    },
    {
        "first_name": "Richard",
        "last_name": "Strauss",
        "birth_year": 1864,
        "death_year": 1949,
        "catalogue": "Op.",
        "pieces": [
            ("Don Juan", "", "20"),
            ("Tod und Verklärung", "", "24"),
            ("Till Eulenspiegels lustige Streiche", "", "28"),
            ("Also sprach Zarathustra", "", "30"),
            ("Don Quixote", "", "35"),
            ("Ein Heldenleben", "", "40"),
            ("Sinfonia domestica", "", "53"),
            ("Der Rosenkavalier", "", "59"),
            ("Eine Alpensinfonie", "", "64"),
            ("Vier letzte Lieder", "", ""),
            ("Oboenkonzert", "D-Dur", ""),
        ],
    },
    {
        "first_name": "Antonín",
        "last_name": "Dvořák",
        "birth_year": 1841,
        "death_year": 1904,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 7", "d-Moll", "70"),
            ("Sinfonie Nr. 8", "G-Dur", "88"),
            ("Sinfonie Nr. 9 «Aus der Neuen Welt»", "e-Moll", "95"),
            ("Cellokonzert", "h-Moll", "104"),
            ("Violinkonzert", "a-Moll", "53"),
            ("Slawische Tänze", "", "46"),
            ("Stabat Mater", "", "58"),
            ("Streichquartett «Amerikanisches»", "F-Dur", "96"),
            ("Serenade für Streicher", "E-Dur", "22"),
        ],
    },
    {
        "first_name": "George Frideric",
        "last_name": "Handel",
        "birth_year": 1685,
        "death_year": 1759,
        "catalogue": "HWV",
        "pieces": [
            ("Messias", "", "56"),
            ("Wassermusik", "", "348"),
            ("Feuerwerksmusik", "", "351"),
            ("Saul", "", "53"),
            ("Solomon", "", "67"),
            ("Giulio Cesare", "", "17"),
        ],
    },
    {
        "first_name": "Joseph",
        "last_name": "Haydn",
        "birth_year": 1732,
        "death_year": 1809,
        "catalogue": "Hob.",
        "pieces": [
            ("Sinfonie Nr. 94 «Mit dem Paukenschlag»", "G-Dur", "I:94"),
            ("Sinfonie Nr. 100 «Militär»", "G-Dur", "I:100"),
            ("Sinfonie Nr. 101 «Die Uhr»", "D-Dur", "I:101"),
            ("Sinfonie Nr. 103 «Mit dem Paukenwirbel»", "Es-Dur", "I:103"),
            ("Sinfonie Nr. 104 «London»", "D-Dur", "I:104"),
            ("Cellokonzert Nr. 1", "C-Dur", "VIIb:1"),
            ("Cellokonzert Nr. 2", "D-Dur", "VIIb:2"),
            ("Trompetenkonzert", "Es-Dur", "VIIe:1"),
            ("Die Schöpfung", "", "XXI:2"),
            ("Die Jahreszeiten", "", "XXI:3"),
            ("Streichquartett «Kaiser»", "C-Dur", "III:77"),
        ],
    },
    {
        "first_name": "Robert",
        "last_name": "Schumann",
        "birth_year": 1810,
        "death_year": 1856,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 1 «Frühlingssinfonie»", "B-Dur", "38"),
            ("Sinfonie Nr. 2", "C-Dur", "61"),
            ("Sinfonie Nr. 3 «Rheinische»", "Es-Dur", "97"),
            ("Sinfonie Nr. 4", "d-Moll", "120"),
            ("Klavierkonzert", "a-Moll", "54"),
            ("Cellokonzert", "a-Moll", "129"),
            ("Violinkonzert", "d-Moll", ""),
            ("Manfred-Ouvertüre", "", "115"),
        ],
    },
    {
        "first_name": "Felix",
        "last_name": "Mendelssohn Bartholdy",
        "birth_year": 1809,
        "death_year": 1847,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 2 «Lobgesang»", "B-Dur", "52"),
            ("Sinfonie Nr. 3 «Schottische»", "a-Moll", "56"),
            ("Sinfonie Nr. 4 «Italienische»", "A-Dur", "90"),
            ("Sinfonie Nr. 5 «Reformationssinfonie»", "d-Moll", "107"),
            ("Violinkonzert", "e-Moll", "64"),
            ("Klavierkonzert Nr. 1", "g-Moll", "25"),
            ("Ouvertüre «Hebriden»", "", "26"),
            ("Ein Sommernachtstraum (Ouvertüre)", "", "21"),
            ("Ein Sommernachtstraum (Schauspielmusik)", "", "61"),
            ("Elias", "", "70"),
        ],
    },
    {
        "first_name": "Antonio",
        "last_name": "Vivaldi",
        "birth_year": 1678,
        "death_year": 1741,
        "catalogue": "RV",
        "pieces": [
            ("La Primavera (Frühling)", "E-Dur", "269"),
            ("L'Estate (Sommer)", "g-Moll", "315"),
            ("L'Autunno (Herbst)", "F-Dur", "293"),
            ("L'Inverno (Winter)", "f-Moll", "297"),
            ("Gloria", "D-Dur", "589"),
            ("Stabat Mater", "f-Moll", "621"),
            ("Flötenkonzert «La notte»", "g-Moll", "439"),
            ("Cellokonzert", "g-Moll", "417"),
            ("Mandolinenkonzert", "C-Dur", "425"),
        ],
    },
    {
        "first_name": "Sergei",
        "last_name": "Rachmaninoff",
        "birth_year": 1873,
        "death_year": 1943,
        "catalogue": "Op.",
        "pieces": [
            ("Klavierkonzert Nr. 1", "fis-Moll", "1"),
            ("Klavierkonzert Nr. 2", "c-Moll", "18"),
            ("Klavierkonzert Nr. 3", "d-Moll", "30"),
            ("Klavierkonzert Nr. 4", "g-Moll", "40"),
            ("Sinfonie Nr. 2", "e-Moll", "27"),
            ("Sinfonie Nr. 3", "a-Moll", "44"),
            ("Symphonische Tänze", "", "45"),
            ("Rhapsodie über ein Thema von Paganini", "", "43"),
            ("Vesper (Ganznächtliche Vigil)", "", "37"),
        ],
    },
    {
        "first_name": "Igor",
        "last_name": "Strawinsky",
        "birth_year": 1882,
        "death_year": 1971,
        "catalogue": "",
        "pieces": [
            ("Der Feuervogel", "", ""),
            ("Petruschka", "", ""),
            ("Le Sacre du printemps", "", ""),
            ("Pulcinella-Suite", "", ""),
            ("Sinfonie der Psalmen", "", ""),
            ("L'histoire du soldat", "", ""),
            ("Apollon musagète", "", ""),
            ("Concerto «Dumbarton Oaks»", "Es-Dur", ""),
        ],
    },
    {
        "first_name": "Dmitri",
        "last_name": "Schostakowitsch",
        "birth_year": 1906,
        "death_year": 1975,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 5", "d-Moll", "47"),
            ("Sinfonie Nr. 7 «Leningrader»", "C-Dur", "60"),
            ("Sinfonie Nr. 8", "c-Moll", "65"),
            ("Sinfonie Nr. 10", "e-Moll", "93"),
            ("Sinfonie Nr. 15", "A-Dur", "141"),
            ("Cellokonzert Nr. 1", "Es-Dur", "107"),
            ("Violinkonzert Nr. 1", "a-Moll", "99"),
            ("Klavierkonzert Nr. 1", "c-Moll", "35"),
            ("Streichquartett Nr. 8", "c-Moll", "110"),
        ],
    },
    {
        "first_name": "Jean",
        "last_name": "Sibelius",
        "birth_year": 1865,
        "death_year": 1957,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 1", "e-Moll", "39"),
            ("Sinfonie Nr. 2", "D-Dur", "43"),
            ("Sinfonie Nr. 5", "Es-Dur", "82"),
            ("Sinfonie Nr. 7", "C-Dur", "105"),
            ("Violinkonzert", "d-Moll", "47"),
            ("Finlandia", "", "26"),
            ("Der Schwan von Tuonela", "", "22"),
            ("En saga", "", "9"),
            ("Tapiola", "", "112"),
        ],
    },
    {
        "first_name": "Maurice",
        "last_name": "Ravel",
        "birth_year": 1875,
        "death_year": 1937,
        "catalogue": "",
        "pieces": [
            ("Boléro", "", ""),
            ("La Valse", "", ""),
            ("Rapsodie espagnole", "", ""),
            ("Klavierkonzert", "G-Dur", ""),
            ("Klavierkonzert für die linke Hand", "D-Dur", ""),
            ("Pavane pour une infante défunte", "", ""),
            ("Daphnis et Chloé (Suite Nr. 2)", "", ""),
            ("Ma Mère l'Oye (Suite)", "", ""),
            ("Alborada del gracioso", "", ""),
            ("Le Tombeau de Couperin", "", ""),
        ],
    },
    {
        "first_name": "Claude",
        "last_name": "Debussy",
        "birth_year": 1862,
        "death_year": 1918,
        "catalogue": "",
        "pieces": [
            ("Prélude à l'après-midi d'un faune", "", ""),
            ("La Mer", "", ""),
            ("Nocturnes", "", ""),
            ("Images pour orchestre", "", ""),
            ("Pelléas et Mélisande", "", ""),
            ("Streichquartett", "g-Moll", ""),
        ],
    },
    {
        "first_name": "Sergei",
        "last_name": "Prokofjew",
        "birth_year": 1891,
        "death_year": 1953,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 1 «Klassische»", "D-Dur", "25"),
            ("Sinfonie Nr. 5", "B-Dur", "100"),
            ("Klavierkonzert Nr. 1", "Des-Dur", "10"),
            ("Klavierkonzert Nr. 2", "g-Moll", "16"),
            ("Klavierkonzert Nr. 3", "C-Dur", "26"),
            ("Violinkonzert Nr. 1", "D-Dur", "19"),
            ("Violinkonzert Nr. 2", "g-Moll", "63"),
            ("Romeo und Julia", "", "64"),
            ("Peter und der Wolf", "", "67"),
            ("Leutnant Kijé (Suite)", "", "60"),
            ("Cinderella", "", "87"),
        ],
    },
    {
        "first_name": "Richard",
        "last_name": "Wagner",
        "birth_year": 1813,
        "death_year": 1883,
        "catalogue": "WWV",
        "pieces": [
            ("Der fliegende Holländer", "", "63"),
            ("Tannhäuser", "", "70"),
            ("Lohengrin", "", "75"),
            ("Das Rheingold", "", "86A"),
            ("Die Walküre", "", "86B"),
            ("Siegfried", "", "86C"),
            ("Götterdämmerung", "", "86D"),
            ("Tristan und Isolde", "", "90"),
            ("Die Meistersinger von Nürnberg", "", "96"),
            ("Parsifal", "", "111"),
            ("Siegfried-Idyll", "E-Dur", "103"),
        ],
    },
    {
        "first_name": "Giuseppe",
        "last_name": "Verdi",
        "birth_year": 1813,
        "death_year": 1901,
        "catalogue": "",
        "pieces": [
            ("Requiem", "", ""),
            ("Otello", "", ""),
            ("Falstaff", "", ""),
            ("Aida", "", ""),
            ("La Traviata", "", ""),
            ("Rigoletto", "", ""),
            ("Il Trovatore", "", ""),
            ("Macbeth", "", ""),
            ("Un ballo in maschera", "", ""),
            ("Nabucco", "", ""),
            ("Simon Boccanegra", "", ""),
            ("Don Carlos", "", ""),
        ],
    },
    {
        "first_name": "Hector",
        "last_name": "Berlioz",
        "birth_year": 1803,
        "death_year": 1869,
        "catalogue": "Op.",
        "pieces": [
            ("Symphonie fantastique", "", "14"),
            ("Harold en Italie", "", "16"),
            ("Roméo et Juliette", "", "17"),
            ("Grande Messe des morts (Requiem)", "", "5"),
            ("La Damnation de Faust", "", "24"),
            ("L'enfance du Christ", "", "25"),
            ("Ouvertüre «Le Carnaval romain»", "", "9"),
            ("Les Troyens", "", ""),
        ],
    },
    {
        "first_name": "Frédéric",
        "last_name": "Chopin",
        "birth_year": 1810,
        "death_year": 1849,
        "catalogue": "Op.",
        "pieces": [
            ("Klavierkonzert Nr. 1", "e-Moll", "11"),
            ("Klavierkonzert Nr. 2", "f-Moll", "21"),
        ],
    },
    {
        "first_name": "Edward",
        "last_name": "Elgar",
        "birth_year": 1857,
        "death_year": 1934,
        "catalogue": "Op.",
        "pieces": [
            ("Enigma-Variationen", "", "36"),
            ("Cellokonzert", "e-Moll", "85"),
            ("Violinkonzert", "h-Moll", "61"),
            ("Sinfonie Nr. 1", "As-Dur", "55"),
            ("Sinfonie Nr. 2", "Es-Dur", "63"),
            ("Introduction and Allegro", "", "47"),
            ("Pomp and Circumstance Marsch Nr. 1", "", "39"),
        ],
    },
    {
        "first_name": "Béla",
        "last_name": "Bartók",
        "birth_year": 1881,
        "death_year": 1945,
        "catalogue": "Sz.",
        "pieces": [
            ("Konzert für Orchester", "", "116"),
            ("Musik für Saiteninstrumente, Schlagzeug und Celesta", "", "106"),
            ("Klavierkonzert Nr. 2", "", "95"),
            ("Klavierkonzert Nr. 3", "", "119"),
            ("Violinkonzert Nr. 2", "", "112"),
            ("Streichquartett Nr. 4", "", "91"),
            ("Herzog Blaubarts Burg", "", "48"),
            ("Der wunderbare Mandarin", "", "73"),
        ],
    },
    {
        "first_name": "Camille",
        "last_name": "Saint-Saëns",
        "birth_year": 1835,
        "death_year": 1921,
        "catalogue": "Op.",
        "pieces": [
            ("Sinfonie Nr. 3 «Orgelsinfonie»", "c-Moll", "78"),
            ("Klavierkonzert Nr. 2", "g-Moll", "22"),
            ("Klavierkonzert Nr. 4", "c-Moll", "44"),
            ("Cellokonzert Nr. 1", "a-Moll", "33"),
            ("Violinkonzert Nr. 3", "h-Moll", "61"),
            ("Der Karneval der Tiere", "", ""),
            ("Danse macabre", "", "40"),
            ("Introduction et Rondo capriccioso", "", "28"),
            ("Havanaise", "", "83"),
        ],
    },
    {
        "first_name": "Franz",
        "last_name": "Liszt",
        "birth_year": 1811,
        "death_year": 1886,
        "catalogue": "S.",
        "pieces": [
            ("Klavierkonzert Nr. 1", "Es-Dur", "124"),
            ("Klavierkonzert Nr. 2", "A-Dur", "125"),
            ("Symphonische Dichtung «Les Préludes»", "", "97"),
            ("A Faust-Sinfonie", "", "108"),
            ("Dante-Sinfonie", "", "109"),
            ("Totentanz", "", "126"),
            ("Klaviersonate", "h-Moll", "178"),
            ("Ungarische Rhapsodien", "", "244"),
        ],
    },
]

# ---------------------------------------------------------------------------
# Artists — conductors and soloists commonly found in concert programmes
# Fields: first_name, last_name, instrument (None = conductor by convention)
# ---------------------------------------------------------------------------
ARTISTS: list[dict] = [
    # Conductors
    {"first_name": "Herbert von", "last_name": "Karajan", "instrument": "Dirigent"},
    {"first_name": "Leonard", "last_name": "Bernstein", "instrument": "Dirigent"},
    {"first_name": "Carlos", "last_name": "Kleiber", "instrument": "Dirigent"},
    {"first_name": "Georg", "last_name": "Solti", "instrument": "Dirigent"},
    {"first_name": "Claudio", "last_name": "Abbado", "instrument": "Dirigent"},
    {"first_name": "Bruno", "last_name": "Walter", "instrument": "Dirigent"},
    {"first_name": "Otto", "last_name": "Klemperer", "instrument": "Dirigent"},
    {"first_name": "Wilhelm", "last_name": "Furtwängler", "instrument": "Dirigent"},
    {"first_name": "Riccardo", "last_name": "Muti", "instrument": "Dirigent"},
    {"first_name": "Simon", "last_name": "Rattle", "instrument": "Dirigent"},
    {"first_name": "Mariss", "last_name": "Jansons", "instrument": "Dirigent"},
    {"first_name": "Bernard", "last_name": "Haitink", "instrument": "Dirigent"},
    {"first_name": "Colin", "last_name": "Davis", "instrument": "Dirigent"},
    {"first_name": "Nikolaus", "last_name": "Harnoncourt", "instrument": "Dirigent"},
    {"first_name": "Daniel", "last_name": "Barenboim", "instrument": "Dirigent"},
    {"first_name": "Andris", "last_name": "Nelsons", "instrument": "Dirigent"},
    {"first_name": "Gustavo", "last_name": "Dudamel", "instrument": "Dirigent"},
    {"first_name": "Yannick", "last_name": "Nézet-Séguin", "instrument": "Dirigent"},
    {"first_name": "Franz", "last_name": "Welser-Möst", "instrument": "Dirigent"},
    # Pianists
    {"first_name": "Martha", "last_name": "Argerich", "instrument": "Klavier"},
    {"first_name": "Vladimir", "last_name": "Horowitz", "instrument": "Klavier"},
    {"first_name": "Arthur", "last_name": "Rubinstein", "instrument": "Klavier"},
    {"first_name": "Glenn", "last_name": "Gould", "instrument": "Klavier"},
    {"first_name": "Sviatoslav", "last_name": "Richter", "instrument": "Klavier"},
    {"first_name": "Emil", "last_name": "Gilels", "instrument": "Klavier"},
    {"first_name": "Mitsuko", "last_name": "Uchida", "instrument": "Klavier"},
    {"first_name": "Murray", "last_name": "Perahia", "instrument": "Klavier"},
    {"first_name": "Lang", "last_name": "Lang", "instrument": "Klavier"},
    {"first_name": "Yuja", "last_name": "Wang", "instrument": "Klavier"},
    {"first_name": "Maurizio", "last_name": "Pollini", "instrument": "Klavier"},
    {"first_name": "Alfred", "last_name": "Brendel", "instrument": "Klavier"},
    {"first_name": "Radu", "last_name": "Lupu", "instrument": "Klavier"},
    {"first_name": "Krystian", "last_name": "Zimerman", "instrument": "Klavier"},
    {"first_name": "Daniil", "last_name": "Trifonov", "instrument": "Klavier"},
    # Violinists
    {"first_name": "Jascha", "last_name": "Heifetz", "instrument": "Violine"},
    {"first_name": "Yehudi", "last_name": "Menuhin", "instrument": "Violine"},
    {"first_name": "David", "last_name": "Oistrakh", "instrument": "Violine"},
    {"first_name": "Isaac", "last_name": "Stern", "instrument": "Violine"},
    {"first_name": "Itzhak", "last_name": "Perlman", "instrument": "Violine"},
    {"first_name": "Anne-Sophie", "last_name": "Mutter", "instrument": "Violine"},
    {"first_name": "Hilary", "last_name": "Hahn", "instrument": "Violine"},
    {"first_name": "Maxim", "last_name": "Vengerov", "instrument": "Violine"},
    {"first_name": "Gidon", "last_name": "Kremer", "instrument": "Violine"},
    {"first_name": "Arthur", "last_name": "Grumiaux", "instrument": "Violine"},
    {"first_name": "Julia", "last_name": "Fischer", "instrument": "Violine"},
    {"first_name": "Renaud", "last_name": "Capuçon", "instrument": "Violine"},
    {"first_name": "Lisa", "last_name": "Batiashvili", "instrument": "Violine"},
    # Cellists
    {"first_name": "Pablo", "last_name": "Casals", "instrument": "Violoncello"},
    {"first_name": "Mstislav", "last_name": "Rostropowitsch", "instrument": "Violoncello"},
    {"first_name": "Jacqueline", "last_name": "du Pré", "instrument": "Violoncello"},
    {"first_name": "Yo-Yo", "last_name": "Ma", "instrument": "Violoncello"},
    {"first_name": "Mischa", "last_name": "Maisky", "instrument": "Violoncello"},
    {"first_name": "Heinrich", "last_name": "Schiff", "instrument": "Violoncello"},
    {"first_name": "Gautier", "last_name": "Capuçon", "instrument": "Violoncello"},
    {"first_name": "Sol", "last_name": "Gabetta", "instrument": "Violoncello"},
    # Wind soloists
    {"first_name": "James", "last_name": "Galway", "instrument": "Flöte"},
    {"first_name": "Emmanuel", "last_name": "Pahud", "instrument": "Flöte"},
    {"first_name": "Sabine", "last_name": "Meyer", "instrument": "Klarinette"},
    {"first_name": "Heinz", "last_name": "Holliger", "instrument": "Oboe"},
    {"first_name": "Maurice", "last_name": "André", "instrument": "Trompete"},
]


def seed_reference_data(session: Session) -> None:
    """Insert reference composers, pieces and artists into a fresh database."""
    composer_count = 0
    piece_count = 0

    for entry in COMPOSERS:
        composer = Composer(
            first_name=entry["first_name"],
            last_name=entry["last_name"],
            birth_year=entry["birth_year"],
            death_year=entry["death_year"],
            catalogue=entry["catalogue"],
        )
        session.add(composer)
        for title, key, cat_number in entry["pieces"]:
            piece = Piece(title=title, key=key, catalogue_number=cat_number)
            composer.pieces.append(piece)
            piece_count += 1
        composer_count += 1

    artist_count = 0
    for a in ARTISTS:
        artist = Artist(
            first_name=a["first_name"],
            last_name=a["last_name"],
            default_instrument=a.get("instrument"),
        )
        session.add(artist)
        artist_count += 1

    logger.info(
        "Seeded reference data: {} composers, {} pieces, {} artists",
        composer_count,
        piece_count,
        artist_count,
    )
